In [1]:
!pip install billboard.py

Collecting billboard.py
  Downloading billboard.py-7.1.0-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.13/dist-packages (from billboard.py) (4.13.5)
Requirement already satisfied: requests>=2.2.1 in /usr/local/lib/python3.13/dist-packages (from billboard.py) (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4>=4.4.1->billboard.py) (2.10)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4>=4.4.1->billboard.py) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.2.1->billboard.py) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.2.1->billboard.py) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.2.1->billboard.py) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.2.1->billboard.py) (2026.7.22)
Downloading billboard.py-7.1.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: billboard.py
Successfully installed billboard.py-7.1.0

In [ ]:
# billboard to load data from Billboard.com
import billboard
# pandas to convert data into DataFrame
import pandas as pd

### Get top 10 artists from 2009 to 2024
- `artists:` top 10 artists in all years.
- `year:` to use it when loading songs.
- `cnt:` to stop itration when we get top 10 every year.
- `chart:` data from Billboard which include artists names and title of songs

In [ ]:
artists = []
year = 2024
for y in range(2025-2009):
    chart = billboard.ChartData('Top-Artists', year=year)
    cnt = 0
    for chr in chart:
        cnt += 1
        if chr.artist not in artists:
                artists.append(chr.artist)
        if cnt == 10:
            break

    year -= 1

len(artists)

68

### Make a method to load data from Billboard
<b>prameters: </b>
- `type:` type of chart we get from Billboard.
- `data:` list of dictionary we collocet data into.
- `artists:` list of artists names.
- `titles:` list of songs name use it to avoid repeat songs.
- `year:` use it when collect popular data.
- `date:` use it when collect unpopular data.
- `year:` use it when collect popular data.
- `label:` 1 if popular and 0 if unpopular.

In [ ]:
def getData(type, data, artists, titles, year=None, date=None, label=None):
    if date==None:
        HotChart = billboard.ChartData(type, year=year)
    else:
        HotChart = billboard.ChartData(type, date=date)
    for hot in HotChart:
        # To collect the name of artists that exists in the artist's list and choose another song for the same artist.
        # This is to avoid repeat songs and enter artist doesn't exist in artists list.
        if hot.title not in titles and hot.artist in artists:
                titles.append(hot.title)
                data.append({'Artist': hot.artist, 'Title': hot.title, 'Label': label})

    return data, titles

### Here I collect popular data from 2009 to 2024

In [ ]:
data = []
titles = []
year = 2024
for i in range(2025-2009):
    data, titles = getData('Hot-100-Songs', data, artists, titles, year, label=1) # popular songs
    year -= 1

In [ ]:
print(len(data))
print(len(artists))
print(len(titles))

395
68
395

### Here I collect popular data from 2009 to 2024 I use another songs that I don't use in popular data
I split the year into 4 splits to get a lot of songs with the same artists which I choose and used the same techniques for every year.

In [ ]:
dates = ['2024-12-01','2024-08-01','2024-04-01','2024-01-01',
        '2023-12-01','2023-08-01','2023-04-01','2023-01-01',
        '2022-12-01','2022-08-01','2022-04-01','2022-01-01',
        '2021-12-01','2021-08-01','2021-04-01','2021-01-01',
        '2020-12-01','2020-08-01','2020-04-01','2020-01-01',
        '2019-12-01','2019-08-01','2019-04-01','2019-01-01',
        '2018-12-01','2018-08-01','2018-04-01','2018-01-01',
        '2017-12-01','2017-08-01','2017-04-01','2017-01-01',
        '2016-12-01','2016-08-01','2016-04-01','2016-01-01',
        '2015-12-01','2015-08-01','2015-04-01','2015-01-01',
        '2014-12-01','2014-08-01','2014-04-01','2014-01-01',
        '2013-12-01','2013-08-01','2013-04-01','2013-01-01',
        '2012-12-01','2012-08-01','2012-04-01','2012-01-01',
        '2011-12-01','2011-08-01','2011-04-01','2011-01-01',
        '2010-12-01','2010-08-01','2010-04-01','2010-01-01',
        '2009-12-01','2009-08-01','2009-04-01','2009-01-01',]
for date in dates:
    data, titles = getData('hot-100', data, artists, titles, date=date, label=0) # unpopular songs

In [ ]:
print(len(data))
print(len(artists))
print(len(titles))

797
68
797

### Convert data to dataframe by using pandas

In [ ]:
df = pd.DataFrame(data)
df

                Artist                 Title  Label
0       Kendrick Lamar           Not Like Us      1
1    Sabrina Carpenter              Espresso      1
2         Taylor Swift          Cruel Summer      1
3        Billie Eilish    Birds Of A Feather      1
4    Sabrina Carpenter  Please Please Please      1
..                 ...                   ...    ...
792         Katy Perry       Thinking Of You      0
793        Miley Cyrus     Hoedown Throwdown      0
794       Taylor Swift      You're Not Sorry      0
795            Rihanna                 Rehab      0
796              Usher        Trading Places      0

[797 rows x 3 columns]

In [ ]:
df[df['Artist']=='Drake'] #getting list of all songs of particular artist

    Artist                     Title  Label
45   Drake           Search & Rescue      1
101  Drake               What's Next      1
117  Drake              Toosie Slide      1
158  Drake                God's Plan      1
160  Drake            In My Feelings      1
161  Drake             Nice For What      1
172  Drake                   Nonstop      1
181  Drake                 I'm Upset      1
193  Drake                 Fake Love      1
203  Drake              Passionfruit      1
219  Drake             Hotline Bling      1
225  Drake                 Controlla      1
260  Drake              Back To Back      1
274  Drake   0 To 100 / The Catch Up      1
282  Drake   Started From The Bottom      1
344  Drake                 Headlines      1
354  Drake            Find Your Love      1
360  Drake                      Over      1
375  Drake           Best I Ever Had      1
425  Drake        You Broke My Heart      0
433  Drake            Virginia Beach      0
434  Drake                Red Button      0
435  Drake             The Shoe Fits      0
438  Drake  Stories About My Brother      0
439  Drake                  Wick Man      0
475  Drake           BackOutsideBoyz      0
478  Drake     Jumbotron Shit Poppin      0
485  Drake       Middle Of The Ocean      0
486  Drake                    Sticky      0
491  Drake                   Massive      0
616  Drake                  Mob Ties      0
620  Drake               Emotionless      0
621  Drake         Can't Take A Joke      0
642  Drake                     Signs      0
656  Drake               Childs Play      0
657  Drake            Summer Sixteen      0
666  Drake                Right Hand      0
686  Drake                    Energy      0
688  Drake             Know Yourself      0
690  Drake                    Legend      0
692  Drake                  10 Bands      0
710  Drake              The Language      0
715  Drake            Worst Behavior      0
756  Drake       Hate Sleeping Alone      0
758  Drake               Shot For Me      0
764  Drake              Marvins Room      0

### Save data as csv file

In [ ]:
df.to_csv('billboard_data_01.csv', index=False)

In [ ]:
dataset = pd.read_csv('billboard_data_01.csv')
dataset

                Artist                 Title  Label
0       Kendrick Lamar           Not Like Us      1
1    Sabrina Carpenter              Espresso      1
2         Taylor Swift          Cruel Summer      1
3        Billie Eilish    Birds Of A Feather      1
4    Sabrina Carpenter  Please Please Please      1
..                 ...                   ...    ...
788         Katy Perry       Thinking Of You      0
789        Miley Cyrus     Hoedown Throwdown      0
790       Taylor Swift      You're Not Sorry      0
791            Rihanna                 Rehab      0
792              Usher        Trading Places      0

[793 rows x 3 columns]

## Download music file from youtube **🎵**

In [ ]:
!pip install youtube-dl
!pip install yt_dlp

Defaulting to user installation because normal site-packages is not writeable
Collecting youtube-dl
  Using cached youtube_dl-2021.12.17-py2.py3-none-any.whl.metadata (1.5 kB)
Using cached youtube_dl-2021.12.17-py2.py3-none-any.whl (1.9 MB)
Installing collected packages: youtube-dl
Successfully installed youtube-dl-2021.12.17
Defaulting to user installation because normal site-packages is not writeable
Collecting yt_dlp
  Using cached yt_dlp-2025.9.26-py3-none-any.whl.metadata (175 kB)
Using cached yt_dlp-2025.9.26-py3-none-any.whl (3.2 MB)
Installing collected packages: yt_dlp
Successfully installed yt_dlp-2025.9.26

In [ ]:
# import all necessary libraries
from __future__ import unicode_literals
import youtube_dl # slow
import pandas as pd
import yt_dlp
import pickle

In [ ]:
data = pd.read_csv('billboard_data_01.csv')
data.head()

              Artist                 Title  Label
0     Kendrick Lamar           Not Like Us      1
1  Sabrina Carpenter              Espresso      1
2       Taylor Swift          Cruel Summer      1
3      Billie Eilish    Birds Of A Feather      1
4  Sabrina Carpenter  Please Please Please      1

In [ ]:
popular_song_titles = list(data.loc[data['Label']==1, 'Title']) # list of song titles on popular chart
unpopular_song_titles = list(data.loc[data['Label']==0, 'Title']) # list for songs on unpopular chart
popular_artists = list(data.loc[data['Label']==1, 'Artist'])  #list for artists on popular chart
unpopular_artists = list(data.loc[data['Label']==0, 'Artist'])  #list for artists on unpopular chart
len(unpopular_song_titles)

400

In [ ]:
#giving a path so that we can save
popular_links_path = r'C:\Users\Arfan\OneDrive\Desktop\ML_Data\popular'
unpopular_links_path = r'C:\Users\Arfan\OneDrive\Desktop\ML_Data\unpopular'

In [ ]:
# helper function to download mp3 songs of specific sonf from artist
def download_audio(song_name,artist, dir_name):
    dir = f'{dir_name}/{song_name}' # directory to store popular / unpopular songs
    filename = f'{dir}.mp3'
    ytdl_opts = {'format': 'bestaudio/best', # best audio format
                "outtmpl": filename, #output format with mp3 extension
                'noplaylist': True, # disable download playlist
                'cookiefile': r"C:\Users\Arfan\OneDrive\Desktop\ML_Data\www.youtube.com_cookies.txt",
                'quiet': True,
                'ignoreerrors': True,   # <-- THIS LINE SKIPS FAILING VIDEOS
                'no_warnings': True,
                }
    song_info =  yt_dlp.YoutubeDL().extract_info(f"ytsearch:{song_name}-{artist}", download=False) # search for song with specific artist name
    with yt_dlp.YoutubeDL(ytdl_opts) as ydl:
        try:
            ydl.download([song_info['webpage_url']])
        except:
            print('could not download song')

### Download full songs with popular song titles

In [ ]:
import os
popular_downloaded_dir = popular_links_path # path to already downloaded popular songs
popular_songs_downloaded = os.listdir(popular_downloaded_dir) # list of already downloaded popular songs
popular_songs_downloaded = [song.replace('.mp3','') for song in popular_songs_downloaded] # get song names from already downloaded list
len(popular_songs_downloaded)

393

In [ ]:
import time
import random
for song, artist in zip(popular_song_titles[:], popular_artists[:]): # iterate through the popular songs to download
    if song not in popular_songs_downloaded: # check if song is already downloaded
        #print(song)
        download_audio(song ,artist, popular_links_path)
        time.sleep(random.randint(5, 10))
    else:
        print('song already exists')

song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
[youtube:search] Extracting URL: ytsearch:Is It Over Now? (Taylor's Version) [From The Vault]-Taylor Swift
[download] Downloading playlist: Is It Over Now? (Taylor's Version) [From The Vault]-Taylor Swift
[youtube:search] query "Is It Over Now? (Taylor's Version) [From The Vault]-Taylor Swift": Downloading web client config
[youtube:search] query "Is It Over Now? (Taylor's Version) [From The Vault]-Taylor Swift" page 1: Downloading API JSON
[youtube:search] Playlist Is It Over Now? (Taylor's Version) [From The Vault]-Taylor Swift: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=tNxUxm3-658
[youtube] tNxUxm3-658: Downloading webpage
[youtube] tNxUxm3-658: Downloading tv client config
[youtube] tNxUxm3-658: Downloading tv player API JSON
[youtube] tNxUxm3-658: Downloading web safari player API JSON
[youtube] tNxUxm3-658: Downloading m3u8 information

WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

[download] Finished downloading playlist: Is It Over Now? (Taylor's Version) [From The Vault]-Taylor Swift
song already exists
song already exists
song already exists
song already exists
[youtube:search] Extracting URL: ytsearch:What Was I Made For?-Billie Eilish
[download] Downloading playlist: What Was I Made For?-Billie Eilish
[youtube:search] query "What Was I Made For?-Billie Eilish": Downloading web client config
[youtube:search] query "What Was I Made For?-Billie Eilish" page 1: Downloading API JSON
[youtube:search] Playlist What Was I Made For?-Billie Eilish: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=cW8VLC9nnTo
[youtube] cW8VLC9nnTo: Downloading webpage
[youtube] cW8VLC9nnTo: Downloading tv client config
[youtube] cW8VLC9nnTo: Downloading tv player API JSON
[youtube] cW8VLC9nnTo: Downloading web safari player API JSON
[youtube] cW8VLC9nnTo: Downloading m3u8 information

WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

[download] Finished downloading playlist: What Was I Made For?-Billie Eilish
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
[youtube:search] Extracting URL: ytsearch:Yes, And?-Ariana Grande
[download] Downloading playlist: Yes, And?-Ariana Grande
[youtube:search] query "Yes, And?-Ariana Grande": Downloading web client config
[youtube:search] query "Yes, And?-Ariana Grande" page 1: Downloading API JSON
[youtube:search] Playlist Yes, And?-Ariana Grande: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=eB6txyhHFG4
[youtube] eB6txyhHFG4: Downloading webpage
[youtube] eB6txyhHFG4: Downloading tv client config
[youtube] eB6txyhHFG4: Downloading tv player API JSON
[youtube] eB6txyhHFG4: Downloading web safari player API JSON
[youtube] eB6txyhHFG4: Downloading m3u8 information

WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

[download] Finished downloading playlist: Yes, And?-Ariana Grande
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
[youtube:search] Extracting URL: ytsearch:How Do You Sleep?-Sam Smith
[download] Downloading playlist: How Do You Sleep?-Sam Smith
[youtube:search] query "How Do You Sleep?-Sam Smith": Downloading web client config
[youtube:search] query "How Do You Sleep?-Sam Smith" page 1: Downloading API JSON
[youtube:search] Playlist How Do You Sleep?-Sam Smith: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=PmYypVozQb4
[youtube] PmYypVozQb4: Downloading webpage
[youtube] PmYypVozQb4: Downloading tv client config
[youtube] PmYypVozQb4: Downloading tv player API JSON
[youtube] PmYypVozQb4: Downloading web safari player API JSON
[youtube] PmYypVozQb4: Downloading m3u8 information

WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

[download] Finished downloading playlist: How Do You Sleep?-Sam Smith
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
[youtube:search] Extracting URL: ytsearch:What Do You Mean?-Justin Bieber
[download] Downloading playlist: What Do You Mean?-Justin Bieber
[youtube:search] query "What Do You Mean?-Justin Bieber": Downloading web client config
[youtube:search] query "What Do You Mean?-Justin Bieber" page 1: Downloading API JSON
[youtube:search] Playlist What Do You Mean?-Justin Bieber: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=DK_0jXPuIr0
[youtube] DK_0jXPuIr0: Downloading webpage
[youtube] DK_0jXPuIr0: Downloading tv client config
[youtube] DK_0jXPuIr0: Downloading tv player API JSON
[youtube] DK_0jXPuIr0: Downloading web safari player API JSON

WARNING: [youtube] DK_0jXPuIr0: Some tv client https formats have been skipped as they are missing a url. YouTube may have enabled the SABR-only or Server-Side Ad Placement experiment for the current session. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] DK_0jXPuIr0: Some web_safari client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
WARNING: [youtube] DK_0jXPuIr0: Some web client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

[youtube] DK_0jXPuIr0: Downloading m3u8 information
[download] Finished downloading playlist: What Do You Mean?-Justin Bieber
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
[youtube:search] Extracting URL: ytsearch:B**** Better Have My Money-Rihanna
[download] Downloading playlist: B**** Better Have My Money-Rihanna
[youtube:search] query "B**** Better Have My Money-Rihanna": Downloading web client config
[youtube:search] query "B**** Better Have My Money-Rihanna" page 1: Downloading API JSON
[youtube:search] Playlist B**** Better Have My Money-Rihanna: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=v_UeJLHdiTk
[youtube] v_UeJLHdiTk: Downloading webpage
[youtube] v_UeJLHdiTk: Downloading tv client config
[youtube] v_UeJLHdiTk: Downloading tv player API JSON
[youtube] v_UeJLHdiTk: Downloading web safari player API JSON
[youtube] v_UeJLHdiTk: Downloading m3u8 information

WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

[download] Finished downloading playlist: B**** Better Have My Money-Rihanna
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
[youtube:search] Extracting URL: ytsearch:F**kin' Perfect-P!nk
[download] Downloading playlist: F**kin' Perfect-P!nk
[youtube:search] query "F**kin' Perfect-P!nk": Downloading web client config
[youtube:search] query "F**kin' Perfect-P!nk" page 1: Downloading API JSON
[youtube:search] Playlist F**kin' Perfect-P!nk: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=d3UqcJFVEsk
[youtube] d3UqcJFVEsk: Downloading webpage
[youtube] d3UqcJFVEsk: Downloading tv client config
[youtube] d3UqcJFVEsk: Downloading tv player API JSON
[youtube] d3UqcJFVEsk: Downloading web safari player API JSON
[youtube] d3UqcJFVEsk: Downloading m3u8 information

WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

[download] Finished downloading playlist: F**kin' Perfect-P!nk
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists

### Download full songs with unpopular song titles

In [ ]:
unpopular_downloaded_dir = unpopular_links_path # path to already downloaded unpopular songs
unpopular_songs_downloaded = os.listdir(unpopular_downloaded_dir) # list of already downloaded unpopular songs
unpopular_songs_downloaded = [song.replace('.mp3','') for song in unpopular_songs_downloaded] # get song names from already downloaded list
len(unpopular_songs_downloaded)

400

In [ ]:
for song, artist in zip(unpopular_song_titles[:], unpopular_artists[:]):
    if song not in unpopular_songs_downloaded:
        #print(song)
        download_audio(song ,artist, unpopular_links_path)
    else:
        print('song already exists')

song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
[youtube:search] Extracting URL: ytsearch:I Know ?-Travis Scott
[download] Downloading playlist: I Know ?-Travis Scott
[youtube:search] query "I Know ?-Travis Scott": Downloading web client config
[youtube:search] query "I Know ?-Travis Scott" page 1: Downloading API JSON
[youtube:search] Playlist I Know ?-Travis Scott: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=X7aF3nZOS98
[youtube] X7aF3nZOS98: Downloading webpage
[youtube] X7aF3nZOS98: Downloading tv client config
[youtube] X7aF3nZOS98: Downloading tv player API JSON
[youtube] X7aF3nZOS98: Downloading web safari player API JSON
[youtube] X7aF3nZOS98: Downloading m3u8 information

WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

[download] Finished downloading playlist: I Know ?-Travis Scott
song already exists
song already exists
song already exists
[youtube:search] Extracting URL: ytsearch:Bad Idea Right?-Olivia Rodrigo
[download] Downloading playlist: Bad Idea Right?-Olivia Rodrigo
[youtube:search] query "Bad Idea Right?-Olivia Rodrigo": Downloading web client config
[youtube:search] query "Bad Idea Right?-Olivia Rodrigo" page 1: Downloading API JSON
[youtube:search] Playlist Bad Idea Right?-Olivia Rodrigo: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=Dj9qJsJTsjQ
[youtube] Dj9qJsJTsjQ: Downloading webpage
[youtube] Dj9qJsJTsjQ: Downloading tv client config
[youtube] Dj9qJsJTsjQ: Downloading tv player API JSON
[youtube] Dj9qJsJTsjQ: Downloading web safari player API JSON
[youtube] Dj9qJsJTsjQ: Downloading m3u8 information

WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

[download] Finished downloading playlist: Bad Idea Right?-Olivia Rodrigo
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
[youtube:search] Extracting URL: ytsearch:Question...?-Taylor Swift
[download] Downloading playlist: Question...?-Taylor Swift
[youtube:search] query "Question...?-Taylor Swift": Downloading web client config
[youtube:search] query "Question...?-Taylor Swift" page 1: Downloading API JSON
[youtube:search] Playlist Question...?-Taylor Swift: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=xxrf_QBD5DE
[youtube] xxrf_QBD5DE: Downloading webpage
[youtube] xxrf_QBD5DE: Downloading tv client config
[youtube] xxrf_QBD5DE: Downloading tv player API JSON
[youtube] xxrf_QBD5DE: Downloading web safari player API JSON
[youtube] xxrf_QBD5DE: Downloading m3u8 information

WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

[download] Finished downloading playlist: Question...?-Taylor Swift
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
[youtube:search] Extracting URL: ytsearch:...Ready For It?-Taylor Swift
[download] Downloading playlist: ...Ready For It?-Taylor Swift
[youtube:search] query "...Ready For It?-Taylor Swift": Downloading web client config
[youtube:search] query "...Ready For It?-Taylor Swift" page 1: Downloading API JSON
[youtube:search] Playlist ...Ready For It?-Taylor Swift: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=wIft-t-MQuE
[youtube] wIft-t-MQuE: Downloading webpage
[youtube] wIft-t-MQuE: Downloading tv client config
[youtube] wIft-t-MQuE: Downloading tv player API JSON
[youtube] wIft-t-MQuE: Downloading web safari player API JSON
[youtube] wIft-t-MQuE: Downloading m3u8 information

WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

[download] Finished downloading playlist: ...Ready For It?-Taylor Swift
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
[youtube:search] Extracting URL: ytsearch:Work B**ch!-Britney Spears
[download] Downloading playlist: Work B**ch!-Britney Spears
[youtube:search] query "Work B**ch!-Britney Spears": Downloading web client config
[youtube:search] query "Work B**ch!-Britney Spears" page 1: Downloading API JSON
[youtube:search] Playlist Work B**ch!-Britney Spears: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=pt8VYOfr8To
[youtube] pt8VYOfr8To: Downloading webpage
[youtube] pt8VYOfr8To: Downloading tv client config
[youtube] pt8VYOfr8To: Downloading tv player API JSON
[youtube] pt8VYOfr8To: Downloading web safari player API JSON
[youtube] pt8VYOfr8To: Downloading m3u8 information

WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

[download] Finished downloading playlist: Work B**ch!-Britney Spears
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists
song already exists

In [ ]:
song_path = [] # list to contain path of donloaded popular & unpopular songs
for song in popular_song_titles:
    if song in popular_songs_downloaded:
        song_path.append(r'popular\{song}.mp3'.format(song=song)) # add popular downloaded songs to list
    else:
        song_path.append(f'n/a')

In [ ]:
for song in unpopular_song_titles:
    if song in unpopular_songs_downloaded:
        song_path.append(r'unpopular\{song}.mp3'.format(song=song)) # add unpopular downloaded songs to song path list
    else:
        song_path.append(f'n/a')

In [ ]:
song_path[:10]

['popular\\Not Like Us.mp3',
 'popular\\Espresso.mp3',
 'popular\\Cruel Summer.mp3',
 'popular\\Birds Of A Feather.mp3',
 'popular\\Please Please Please.mp3',
 'popular\\Agora Hills.mp3',
 'popular\\Saturn.mp3',
 'popular\\Snooze.mp3',
 'popular\\Paint The Town Red.mp3',
 'popular\\Fast Car.mp3']

In [ ]:
len(song_path)

793

In [ ]:
data =data.assign(song_path=song_path) # add new list to existing data table
data

,Artist,Title,Label,song_path
0,Kendrick Lamar,Not Like Us,1,popular\Not Like Us.mp3
1,Sabrina Carpenter,Espresso,1,popular\Espresso.mp3
2,Taylor Swift,Cruel Summer,1,popular\Cruel Summer.mp3
3,Billie Eilish,Birds Of A Feather,1,popular\Birds Of A Feather.mp3
4,Sabrina Carpenter,Please Please Please,1,popular\Please Please Please.mp3
...,...,...,...,...
788,Katy Perry,Thinking Of You,0,unpopular\Thinking Of You.mp3
789,Miley Cyrus,Hoedown Throwdown,0,unpopular\Hoedown Throwdown.mp3
790,Taylor Swift,You're Not Sorry,0,unpopular\You're Not Sorry.mp3
791,Rihanna,Rehab,0,unpopular\Rehab.mp3
792,Usher,Trading Places,0,unpopular\Trading Places.mp3

In [ ]:
data.to_csv('billboard_fullsongs_02.csv', index=False)

# Extract 15s Chorus

In [2]:
!pip install pychorus

Collecting pychorus
  Downloading pychorus-v0.1.tar.gz (5.1 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: librosa in /usr/local/lib/python3.13/dist-packages (from pychorus) (0.11.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from pychorus) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from pychorus) (1.16.3)
Requirement already satisfied: soundfile in /usr/local/lib/python3.13/dist-packages (from pychorus) (0.14.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from pychorus) (3.10.0)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.13/dist-packages (from librosa->pychorus) (3.1.0)
Requirement already satisfied: numba>=0.51.0 in /usr/local/lib/python3.13/dist-packages (from librosa->pychorus) (0.61.2)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from librosa->pychorus) (1.6.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.13/dist-packages (from librosa->pychorus) (1.6.0)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.13/dist-packages (from librosa->pychorus) (4.4.2)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.13/dist-packages (from librosa->pychorus) (1.9.0)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.13/dist-packages (from librosa->pychorus) (1.1.0)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.13/dist-packages (from librosa->pychorus) (4.16.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/local/lib/python3.13/dist-packages (from librosa->pychorus) (0.6)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.13/dist-packages (from librosa->pychorus) (1.2.3)
Requirement already satisfied: standard-aifc in /usr/local/lib/python3.13/dist-packages (from librosa->pychorus) (3.13.0)
Requirement already satisfied: standard-sunau in /usr/local/lib/python3.13/dist-packages (from librosa->pychorus) (3.13.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.13/dist-packages (from soundfile->pychorus) (2.1.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->pychorus) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->pychorus) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->pychorus) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->pychorus) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->pychorus) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->pychorus) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->pychorus) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib->pychorus) (2.9.0.post0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=1.0->soundfile->pychorus) (3.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.0->librosa->pychorus) (3.1.2)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba>=0.51.0->librosa->pychorus) (0.44.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from pooch>=1.1->librosa->pychorus) (4.12.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.13/dist-packages (from pooch>=1.1->librosa->pychorus) (2.32.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib->pychorus) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.1.0->librosa->pychorus) (3.7.0)
Requirement already satisfied: standard-chunk in /usr/local/lib/python3.13/dist-packages (from standard-aifc->librosa->pychorus) (3.13.0)
Requirement already satisfied: audioop-lts in /usr/local/lib/python3.13/dist-packages (from standard-aifc->librosa->pychorus) (0.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa->pychorus) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa->pychorus) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa->pychorus) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa->pychorus) (2026.7.22)
Building wheels for collected packages: pychorus
  Building wheel for pychorus (setup.py) ... done
  Created wheel for pychorus: filename=pychorus-0.1-py3-none-any.whl size=6488 sha256=044b99f55c9dfea96d2f0bab52fb533abfabeec55d660c6f84d8a0908c3cd061
  Stored in directory: /root/.cache/pip/wheels/7e/04/d1/7d979b5be1f65b153a150deaf491b1d0a951f0170000f462dd
Successfully built pychorus
Installing collected packages: pychorus
Successfully installed pychorus-0.1

In [ ]:
# import necessary libraries
import os
import pandas as pd
import warnings
warnings.filterwarnings(action='ignore')
df=pd.read_csv('billboard_fullsongs_02.csv', encoding='Windows-1252')
df

,Artist,Title,Label,song_path
0,Kendrick Lamar,Not Like Us,1,popular\Not Like Us.mp3
1,Sabrina Carpenter,Espresso,1,popular\Espresso.mp3
2,Taylor Swift,Cruel Summer,1,popular\Cruel Summer.mp3
3,Billie Eilish,Birds Of A Feather,1,popular\Birds Of A Feather.mp3
4,Sabrina Carpenter,Please Please Please,1,popular\Please Please Please.mp3
...,...,...,...,...
788,Katy Perry,Thinking Of You,0,unpopular\Thinking Of You.mp3
789,Miley Cyrus,Hoedown Throwdown,0,unpopular\Hoedown Throwdown.mp3
790,Taylor Swift,You're Not Sorry,0,unpopular\You're Not Sorry.mp3
791,Rihanna,Rehab,0,unpopular\Rehab.mp3
792,Usher,Trading Places,0,unpopular\Trading Places.mp3

In [ ]:
df[df['song_path'].isna()] #check for null paths

,Artist,Title,Label,song_path
16,Taylor Swift,Is It Over Now? (Taylor's Version) [From The V...,1,NaN
21,Billie Eilish,What Was I Made For?,1,NaN
32,Ariana Grande,"Yes, And?",1,NaN
155,Sam Smith,How Do You Sleep?,1,NaN
220,Justin Bieber,What Do You Mean?,1,NaN
250,Rihanna,B**** Better Have My Money,1,NaN
325,P!nk,F**kin' Perfect,1,NaN
433,Travis Scott,I Know ?,0,NaN
437,Olivia Rodrigo,Bad Idea Right?,0,NaN
476,Taylor Swift,Question...?,0,NaN
624,Taylor Swift,...Ready For It?,0,NaN
719,Britney Spears,Work B**ch!,0,NaN

In [ ]:
# dropping null values
df = df.dropna(axis=0)
df

,Artist,Title,Label,song_path
0,Kendrick Lamar,Not Like Us,1,popular\Not Like Us.mp3
1,Sabrina Carpenter,Espresso,1,popular\Espresso.mp3
2,Taylor Swift,Cruel Summer,1,popular\Cruel Summer.mp3
3,Billie Eilish,Birds Of A Feather,1,popular\Birds Of A Feather.mp3
4,Sabrina Carpenter,Please Please Please,1,popular\Please Please Please.mp3
...,...,...,...,...
788,Katy Perry,Thinking Of You,0,unpopular\Thinking Of You.mp3
789,Miley Cyrus,Hoedown Throwdown,0,unpopular\Hoedown Throwdown.mp3
790,Taylor Swift,You're Not Sorry,0,unpopular\You're Not Sorry.mp3
791,Rihanna,Rehab,0,unpopular\Rehab.mp3
792,Usher,Trading Places,0,unpopular\Trading Places.mp3

In [ ]:
df[df['song_path'].isna()]#check for null paths

Empty DataFrame
Columns: [Artist, Title, Label, song_path]
Index: []

In [3]:
!pip install ffmpeg

Collecting ffmpeg
  Downloading ffmpeg-1.4.tar.gz (5.1 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: ffmpeg
  Building wheel for ffmpeg (setup.py) ... done
  Created wheel for ffmpeg: filename=ffmpeg-1.4-py3-none-any.whl size=6126 sha256=4fd5ae40ee3486e56067784be5121af64a0114c3c8e71486149a7452ecd28134
  Stored in directory: /root/.cache/pip/wheels/a4/04/6c/ab972358c48aedc5be02f1d28968f2baa491a2837270932043
Successfully built ffmpeg
Installing collected packages: ffmpeg
Successfully installed ffmpeg-1.4

In [4]:
# changing path of downloaded songs as per my drive path location

new_path = []
root = r"C:\Users\Arfan\OneDrive\Desktop\ML_Data"
for path in df['song_path']:
  cleaned_path = str(path).lstrip('\\')
  new = os.path.join(root, cleaned_path)
  new_path.append(new)

print(new_path[:10])

NameError: name 'df' is not defined

In [5]:
full_songs_path = new_path # list of full songs downloaded path
print(full_songs_path[:10])

[]

In [ ]:
chorus_extract_path = r'C:\Users\Arfan\OneDrive\Desktop\ML_Data\chorus_extract' # path to save extracted chorus

In [ ]:
extracted_songs = [basename.replace('.wav','') for basename in os.listdir(chorus_extract_path)] # basename/ song name of already extracted song to avoid repitition in chorus extraction
# extracted_songs

In [ ]:
from pychorus import find_and_output_chorus # import chorus ectractor lib
not_extrated = [] # list to track not extracted choruses

In [ ]:
# helper function to extract 15s choruses from songs as required in paper
def extract_chorus(path_list, output_path):
    for path in path_list:
        basename = os.path.basename(str(path)).replace('.mp3', '')
        save_path = os.path.join(output_path, f'{basename}.wav')  # output path as .wav extension
        if basename in extracted_songs:
            print('song already exists')
        else:
            chorus = find_and_output_chorus(str(path), str(save_path), 15)
            if chorus == None:
                not_extrated.append(basename)

In [ ]:
extract_chorus(full_songs_path, chorus_extract_path) #extract all choruses

Best chorus found at 4 min 54.12 sec
Best chorus found at 1 min 18.73 sec
Best chorus found at 2 min 4.79 sec
Best chorus found at 0 min 19.68 sec
Best chorus found at 2 min 47.14 sec
Best chorus found at 2 min 13.31 sec
Best chorus found at 1 min 48.99 sec
Best chorus found at 1 min 33.02 sec
Best chorus found at 4 min 4.32 sec
Best chorus found at 3 min 59.16 sec
Best chorus found at 1 min 57.93 sec
Best chorus found at 3 min 27.85 sec
Best chorus found at 1 min 38.25 sec
Best chorus found at 2 min 38.18 sec
Best chorus found at 2 min 9.84 sec
Best chorus found at 2 min 20.17 sec
Best chorus found at 1 min 55.84 sec
Best chorus found at 2 min 51.51 sec
Best chorus found at 2 min 46.77 sec
Best chorus found at 3 min 41.67 sec
Best chorus found at 1 min 53.29 sec
Best chorus found at 2 min 31.16 sec
Best chorus found at 3 min 9.94 sec
No choruses were detected. Try a smaller search duration
Best chorus found at 2 min 19.56 sec
Best chorus found at 1 min 41.57 sec
Best chorus found at 4 min 12.92 sec
Best chorus found at 2 min 20.98 sec
Best chorus found at 2 min 23.76 sec
Best chorus found at 1 min 48.05 sec
Best chorus found at 3 min 13.66 sec
Best chorus found at 3 min 13.08 sec
Best chorus found at 4 min 33.92 sec
Best chorus found at 2 min 0.84 sec
Best chorus found at 3 min 47.83 sec
Best chorus found at 1 min 5.17 sec
Best chorus found at 2 min 27.43 sec
Best chorus found at 2 min 47.30 sec
Best chorus found at 2 min 1.40 sec
Best chorus found at 2 min 59.10 sec
Best chorus found at 2 min 46.42 sec
Best chorus found at 2 min 32.25 sec
Best chorus found at 3 min 58.86 sec
Best chorus found at 2 min 42.12 sec
Best chorus found at 1 min 28.15 sec
Best chorus found at 1 min 18.13 sec
Best chorus found at 1 min 42.52 sec
Best chorus found at 2 min 19.64 sec
Best chorus found at 1 min 59.60 sec
Best chorus found at 2 min 49.70 sec
Best chorus found at 2 min 36.00 sec
Best chorus found at 1 min 53.78 sec
Best chorus found at 1 min 31.86 sec
Best chorus found at 2 min 0.68 sec
Best chorus found at 2 min 16.13 sec
Best chorus found at 1 min 27.67 sec
Best chorus found at 2 min 55.15 sec
Best chorus found at 3 min 5.25 sec
Best chorus found at 2 min 37.88 sec
Best chorus found at 3 min 24.38 sec
Best chorus found at 1 min 27.58 sec
Best chorus found at 2 min 55.27 sec
Best chorus found at 2 min 10.94 sec
Best chorus found at 2 min 31.32 sec
Best chorus found at 3 min 52.85 sec
Best chorus found at 2 min 25.22 sec
Best chorus found at 2 min 41.00 sec
Best chorus found at 2 min 53.74 sec
Best chorus found at 1 min 12.81 sec
Best chorus found at 2 min 37.46 sec
Best chorus found at 2 min 10.18 sec
Best chorus found at 2 min 42.86 sec
Best chorus found at 1 min 47.09 sec
Best chorus found at 2 min 28.15 sec
Best chorus found at 1 min 35.18 sec
Best chorus found at 1 min 47.28 sec
Best chorus found at 2 min 42.10 sec
Best chorus found at 2 min 56.17 sec
Best chorus found at 4 min 37.40 sec
No choruses were detected. Try a smaller search duration
Best chorus found at 0 min 50.86 sec
Best chorus found at 2 min 32.24 sec
Best chorus found at 3 min 22.07 sec
Best chorus found at 1 min 45.68 sec
Best chorus found at 2 min 11.97 sec
Best chorus found at 2 min 17.08 sec
Best chorus found at 2 min 14.07 sec
Best chorus found at 3 min 0.10 sec
Best chorus found at 1 min 16.28 sec
Best chorus found at 4 min 2.59 sec
Best chorus found at 2 min 14.96 sec
Best chorus found at 1 min 59.04 sec
Best chorus found at 2 min 57.88 sec
Best chorus found at 1 min 35.81 sec
Best chorus found at 1 min 57.54 sec
Best chorus found at 3 min 1.93 sec
Best chorus found at 2 min 37.64 sec
Best chorus found at 3 min 38.26 sec
Best chorus found at 1 min 28.04 sec
Best chorus found at 1 min 17.44 sec
Best chorus found at 3 min 36.40 sec
Best chorus found at 1 min 46.81 sec
Best chorus found at 1 min 13.13 sec
Best chorus found at 1 min 32.47 sec
Best chorus found at 1 min 48.44 sec
Best chorus found at 2 min 14.41 sec
Best chorus found at 1 min 40.83 sec
Best chorus found at 3 min 3.79 sec
Best chorus found at 2 min 8.47 sec
Best chorus found at 3 min 19.59 sec
Best chorus found at 2 min 49.59 sec
Best chorus found at 1 min 0.90 sec
Best chorus found at 1 min 42.86 sec
Best chorus found at 2 min 32.75 sec
Best chorus found at 4 min 24.14 sec
Best chorus found at 2 min 35.73 sec
Best chorus found at 2 min 33.87 sec
Best chorus found at 0 min 33.06 sec
Best chorus found at 1 min 46.21 sec
Best chorus found at 3 min 5.35 sec
Best chorus found at 1 min 4.03 sec
Best chorus found at 0 min 46.05 sec
Best chorus found at 2 min 46.36 sec
Best chorus found at 3 min 5.09 sec
Best chorus found at 2 min 51.13 sec
Best chorus found at 2 min 20.79 sec
Best chorus found at 1 min 26.32 sec
Best chorus found at 2 min 33.92 sec
Best chorus found at 1 min 42.49 sec
Best chorus found at 2 min 52.49 sec
Best chorus found at 3 min 18.54 sec
Best chorus found at 2 min 13.64 sec
Best chorus found at 2 min 19.60 sec
Best chorus found at 0 min 42.51 sec
Best chorus found at 1 min 55.87 sec
Best chorus found at 2 min 43.77 sec
Best chorus found at 2 min 39.08 sec
Best chorus found at 2 min 16.28 sec
Best chorus found at 2 min 8.29 sec
Best chorus found at 2 min 51.34 sec
Best chorus found at 2 min 3.84 sec
Best chorus found at 1 min 39.17 sec
Best chorus found at 1 min 30.43 sec
Best chorus found at 5 min 42.82 sec
Best chorus found at 1 min 51.02 sec
Best chorus found at 3 min 4.23 sec
Best chorus found at 3 min 14.56 sec
Best chorus found at 2 min 44.20 sec
Best chorus found at 1 min 21.71 sec
Best chorus found at 1 min 25.43 sec
Best chorus found at 3 min 8.43 sec
Best chorus found at 2 min 46.55 sec
Best chorus found at 2 min 37.47 sec
Best chorus found at 1 min 22.24 sec
Best chorus found at 3 min 27.77 sec
Best chorus found at 3 min 49.48 sec
Best chorus found at 7 min 25.08 sec
Best chorus found at 3 min 52.46 sec
Best chorus found at 2 min 19.44 sec
Best chorus found at 3 min 22.44 sec
Best chorus found at 2 min 50.77 sec
Best chorus found at 1 min 35.58 sec
Best chorus found at 3 min 17.74 sec
Best chorus found at 2 min 22.79 sec
Best chorus found at 3 min 2.02 sec
Best chorus found at 2 min 56.93 sec
Best chorus found at 2 min 37.61 sec
Best chorus found at 3 min 41.32 sec
Best chorus found at 4 min 14.54 sec
Best chorus found at 1 min 45.25 sec
Best chorus found at 1 min 59.44 sec
Best chorus found at 2 min 49.19 sec
Best chorus found at 2 min 57.48 sec
Best chorus found at 2 min 32.50 sec
Best chorus found at 2 min 28.51 sec
Best chorus found at 3 min 18.25 sec
Best chorus found at 2 min 41.40 sec
Best chorus found at 4 min 22.61 sec
Best chorus found at 1 min 30.75 sec
Best chorus found at 0 min 43.06 sec
Best chorus found at 1 min 45.64 sec
Best chorus found at 2 min 49.30 sec
Best chorus found at 2 min 58.60 sec
Best chorus found at 2 min 46.53 sec
Best chorus found at 4 min 10.88 sec
Best chorus found at 3 min 6.11 sec
Best chorus found at 2 min 28.00 sec
Best chorus found at 3 min 9.47 sec
Best chorus found at 3 min 1.65 sec
Best chorus found at 2 min 15.92 sec
Best chorus found at 3 min 3.41 sec
Best chorus found at 3 min 49.89 sec
Best chorus found at 1 min 24.51 sec
Best chorus found at 2 min 37.58 sec
Best chorus found at 4 min 23.18 sec
Best chorus found at 3 min 10.55 sec
Best chorus found at 1 min 30.57 sec
Best chorus found at 2 min 55.27 sec
Best chorus found at 2 min 15.35 sec
Best chorus found at 4 min 26.26 sec
Best chorus found at 3 min 21.45 sec
Best chorus found at 2 min 43.27 sec
Best chorus found at 1 min 27.85 sec
Best chorus found at 1 min 35.82 sec
Best chorus found at 3 min 3.84 sec
Best chorus found at 1 min 55.09 sec
Best chorus found at 1 min 33.24 sec
No choruses were detected. Try a smaller search duration
Best chorus found at 3 min 41.34 sec
Best chorus found at 2 min 47.43 sec
Best chorus found at 2 min 2.92 sec
Best chorus found at 5 min 31.74 sec
Best chorus found at 2 min 53.27 sec
Best chorus found at 3 min 10.54 sec
Best chorus found at 3 min 33.62 sec
Best chorus found at 3 min 17.71 sec
Best chorus found at 2 min 11.11 sec
Best chorus found at 3 min 14.63 sec
Best chorus found at 2 min 41.57 sec
Best chorus found at 3 min 35.52 sec
Best chorus found at 1 min 42.45 sec
Best chorus found at 2 min 26.92 sec
Best chorus found at 5 min 35.10 sec
Best chorus found at 2 min 9.97 sec
Best chorus found at 3 min 37.07 sec
Best chorus found at 3 min 0.55 sec
Best chorus found at 3 min 15.11 sec
Best chorus found at 4 min 14.55 sec
Best chorus found at 3 min 2.32 sec
Best chorus found at 4 min 44.18 sec
Best chorus found at 1 min 53.29 sec
Best chorus found at 2 min 47.91 sec
Best chorus found at 1 min 52.27 sec
Best chorus found at 2 min 8.86 sec
Best chorus found at 2 min 35.93 sec
Best chorus found at 3 min 47.83 sec
Best chorus found at 3 min 36.90 sec
Best chorus found at 3 min 28.75 sec
Best chorus found at 2 min 47.31 sec
Best chorus found at 2 min 31.61 sec
Best chorus found at 3 min 49.36 sec
Best chorus found at 2 min 8.83 sec
Best chorus found at 3 min 33.84 sec
Best chorus found at 3 min 39.27 sec
Best chorus found at 3 min 48.97 sec
Best chorus found at 2 min 55.08 sec
No choruses were detected. Try a smaller search duration
Best chorus found at 1 min 41.16 sec
Best chorus found at 3 min 40.27 sec
Best chorus found at 2 min 49.13 sec
No choruses were detected. Try a smaller search duration
Best chorus found at 2 min 49.01 sec
Best chorus found at 2 min 9.94 sec
Best chorus found at 1 min 52.82 sec
Best chorus found at 3 min 34.07 sec
Best chorus found at 2 min 43.92 sec
Best chorus found at 3 min 29.97 sec
Best chorus found at 2 min 47.59 sec
Best chorus found at 3 min 3.24 sec
Best chorus found at 3 min 9.53 sec
Best chorus found at 3 min 38.17 sec
Best chorus found at 3 min 17.24 sec
Best chorus found at 1 min 58.10 sec
Best chorus found at 2 min 27.10 sec
Best chorus found at 3 min 1.38 sec
Best chorus found at 2 min 57.47 sec
Best chorus found at 2 min 48.92 sec
Best chorus found at 7 min 15.90 sec
Best chorus found at 1 min 56.76 sec
Best chorus found at 3 min 8.29 sec
Best chorus found at 2 min 49.57 sec
Best chorus found at 3 min 1.81 sec
Best chorus found at 3 min 40.44 sec
Best chorus found at 2 min 17.75 sec
Best chorus found at 4 min 1.62 sec
Best chorus found at 2 min 51.93 sec
Best chorus found at 3 min 5.35 sec
Best chorus found at 3 min 17.17 sec
Best chorus found at 1 min 14.27 sec
Best chorus found at 3 min 13.26 sec
Best chorus found at 2 min 20.71 sec
Best chorus found at 0 min 48.28 sec
Best chorus found at 3 min 49.71 sec
Best chorus found at 1 min 25.03 sec
Best chorus found at 2 min 52.08 sec
Best chorus found at 3 min 56.00 sec
Best chorus found at 3 min 30.44 sec
Best chorus found at 2 min 51.25 sec
Best chorus found at 3 min 30.57 sec
Best chorus found at 2 min 57.47 sec
Best chorus found at 2 min 44.83 sec
Best chorus found at 1 min 39.34 sec
Best chorus found at 2 min 1.29 sec
Best chorus found at 1 min 51.40 sec
Best chorus found at 3 min 29.70 sec
Best chorus found at 1 min 35.98 sec
Best chorus found at 3 min 41.36 sec
Best chorus found at 2 min 32.66 sec
Best chorus found at 3 min 19.84 sec
Best chorus found at 2 min 57.00 sec
Best chorus found at 3 min 24.87 sec
Best chorus found at 3 min 26.05 sec
Best chorus found at 3 min 23.32 sec
Best chorus found at 3 min 2.77 sec
Best chorus found at 3 min 1.66 sec
Best chorus found at 3 min 24.18 sec
Best chorus found at 3 min 19.60 sec
Best chorus found at 3 min 5.91 sec
Best chorus found at 3 min 30.80 sec
Best chorus found at 2 min 46.93 sec
Best chorus found at 3 min 4.22 sec
Best chorus found at 2 min 53.29 sec
Best chorus found at 2 min 48.01 sec
Best chorus found at 2 min 9.39 sec
Best chorus found at 3 min 1.83 sec
Best chorus found at 7 min 20.98 sec
Best chorus found at 1 min 25.60 sec
Best chorus found at 2 min 49.09 sec
Best chorus found at 5 min 50.68 sec
Best chorus found at 3 min 42.25 sec
Best chorus found at 2 min 44.13 sec
Best chorus found at 3 min 17.22 sec
Best chorus found at 4 min 1.36 sec
Best chorus found at 3 min 11.36 sec
Best chorus found at 1 min 0.14 sec
Best chorus found at 4 min 25.23 sec
Best chorus found at 3 min 22.25 sec
Best chorus found at 3 min 45.95 sec
Best chorus found at 3 min 44.09 sec
Best chorus found at 2 min 6.61 sec
Best chorus found at 2 min 51.37 sec
Best chorus found at 2 min 47.47 sec
Best chorus found at 3 min 56.92 sec
Best chorus found at 1 min 24.68 sec
Best chorus found at 3 min 42.90 sec
Best chorus found at 3 min 8.09 sec
Best chorus found at 2 min 54.36 sec
Best chorus found at 3 min 11.42 sec
Best chorus found at 2 min 2.97 sec
Best chorus found at 3 min 1.38 sec
Best chorus found at 2 min 57.69 sec
Best chorus found at 3 min 1.11 sec
Best chorus found at 3 min 43.62 sec
Best chorus found at 2 min 49.59 sec
Best chorus found at 2 min 31.75 sec
Best chorus found at 3 min 35.39 sec
Best chorus found at 8 min 5.56 sec
Best chorus found at 1 min 11.14 sec
Best chorus found at 1 min 41.90 sec
Best chorus found at 4 min 0.49 sec
Best chorus found at 2 min 55.97 sec
Best chorus found at 3 min 2.20 sec
Best chorus found at 2 min 33.91 sec
Best chorus found at 2 min 47.08 sec
Best chorus found at 2 min 36.58 sec
Best chorus found at 3 min 2.26 sec
Best chorus found at 3 min 1.95 sec
Best chorus found at 1 min 32.65 sec
Best chorus found at 4 min 12.53 sec
Best chorus found at 3 min 15.32 sec
Best chorus found at 3 min 2.11 sec
Best chorus found at 3 min 6.79 sec
Best chorus found at 2 min 58.69 sec
Best chorus found at 1 min 41.73 sec
Best chorus found at 2 min 38.04 sec
Best chorus found at 2 min 40.29 sec
Best chorus found at 1 min 34.36 sec
Best chorus found at 2 min 13.64 sec
Best chorus found at 3 min 44.12 sec
Best chorus found at 2 min 57.36 sec
Best chorus found at 2 min 9.44 sec
Best chorus found at 1 min 14.64 sec
Best chorus found at 3 min 38.43 sec
Best chorus found at 2 min 51.08 sec
Best chorus found at 2 min 59.95 sec
Best chorus found at 2 min 25.53 sec
Best chorus found at 2 min 48.82 sec
Best chorus found at 3 min 24.95 sec
Best chorus found at 2 min 52.64 sec
Best chorus found at 3 min 15.86 sec
Best chorus found at 2 min 2.51 sec
Best chorus found at 3 min 6.11 sec
Best chorus found at 1 min 51.97 sec
Best chorus found at 2 min 11.88 sec
Best chorus found at 1 min 12.03 sec
Best chorus found at 2 min 59.04 sec
Best chorus found at 1 min 49.38 sec
Best chorus found at 4 min 28.66 sec
No choruses were detected. Try a smaller search duration
Best chorus found at 3 min 28.50 sec
Best chorus found at 4 min 17.75 sec
Best chorus found at 1 min 12.22 sec
Best chorus found at 1 min 57.47 sec
Best chorus found at 2 min 59.50 sec
Best chorus found at 3 min 20.72 sec
No choruses were detected. Try a smaller search duration
Best chorus found at 2 min 12.07 sec
Best chorus found at 3 min 9.78 sec
Best chorus found at 1 min 23.56 sec
Best chorus found at 1 min 34.10 sec
Best chorus found at 1 min 39.87 sec
Best chorus found at 4 min 52.75 sec
Best chorus found at 2 min 31.54 sec
Best chorus found at 4 min 24.51 sec
No choruses were detected. Try a smaller search duration
Best chorus found at 1 min 34.13 sec
Best chorus found at 1 min 10.70 sec
Best chorus found at 1 min 28.75 sec
Best chorus found at 3 min 5.52 sec
Best chorus found at 2 min 14.91 sec
Best chorus found at 2 min 42.14 sec
Best chorus found at 1 min 1.80 sec
Best chorus found at 1 min 17.77 sec
Best chorus found at 2 min 35.18 sec
Best chorus found at 2 min 33.15 sec
No choruses were detected. Try a smaller search duration
Best chorus found at 1 min 20.50 sec
Best chorus found at 2 min 15.04 sec
Best chorus found at 1 min 43.77 sec
Best chorus found at 2 min 41.85 sec
Best chorus found at 0 min 59.20 sec
Best chorus found at 4 min 18.83 sec
Best chorus found at 1 min 22.62 sec
Best chorus found at 1 min 48.99 sec
Best chorus found at 2 min 12.52 sec
Best chorus found at 5 min 46.28 sec
Best chorus found at 1 min 26.70 sec
Best chorus found at 3 min 45.98 sec
No choruses were detected. Try a smaller search duration
Best chorus found at 1 min 39.93 sec
Best chorus found at 3 min 36.01 sec
Best chorus found at 1 min 50.88 sec
Best chorus found at 2 min 3.83 sec
Best chorus found at 2 min 9.47 sec
Best chorus found at 3 min 5.68 sec
Best chorus found at 2 min 24.60 sec
Best chorus found at 5 min 12.91 sec
No choruses were detected. Try a smaller search duration
Best chorus found at 2 min 41.04 sec
Best chorus found at 2 min 31.30 sec
Best chorus found at 2 min 54.13 sec
Best chorus found at 1 min 10.92 sec
Best chorus found at 1 min 28.04 sec
Best chorus found at 2 min 12.87 sec
Best chorus found at 2 min 7.03 sec
Best chorus found at 1 min 44.13 sec
Best chorus found at 2 min 12.96 sec
Best chorus found at 2 min 27.43 sec
Best chorus found at 2 min 26.93 sec
Best chorus found at 2 min 27.99 sec
Best chorus found at 2 min 13.98 sec
Best chorus found at 2 min 29.14 sec
Best chorus found at 2 min 11.85 sec
No choruses were detected. Try a smaller search duration
Best chorus found at 1 min 28.52 sec
Best chorus found at 2 min 27.60 sec
Best chorus found at 2 min 17.34 sec
Best chorus found at 1 min 36.50 sec
No choruses were detected. Try a smaller search duration
Best chorus found at 1 min 24.33 sec
Best chorus found at 4 min 54.23 sec
Best chorus found at 1 min 9.40 sec
Best chorus found at 3 min 0.25 sec
Best chorus found at 1 min 51.71 sec
Best chorus found at 1 min 4.44 sec
Best chorus found at 2 min 5.71 sec
Best chorus found at 1 min 17.61 sec
Best chorus found at 2 min 21.78 sec
Best chorus found at 2 min 5.38 sec
Best chorus found at 2 min 32.21 sec
Best chorus found at 0 min 35.10 sec
Best chorus found at 0 min 59.95 sec
Best chorus found at 3 min 39.14 sec
Best chorus found at 2 min 36.32 sec
Best chorus found at 3 min 59.57 sec
Best chorus found at 3 min 17.61 sec
Best chorus found at 1 min 29.28 sec
Best chorus found at 1 min 1.84 sec
Best chorus found at 3 min 44.33 sec
Best chorus found at 2 min 33.78 sec
Best chorus found at 2 min 2.49 sec
Best chorus found at 2 min 54.84 sec
Best chorus found at 3 min 33.52 sec
Best chorus found at 1 min 56.77 sec
Best chorus found at 1 min 40.27 sec
No choruses were detected. Try a smaller search duration
Best chorus found at 2 min 39.74 sec
Best chorus found at 2 min 0.72 sec
Best chorus found at 3 min 45.50 sec
Best chorus found at 2 min 3.13 sec
Best chorus found at 1 min 55.26 sec
Best chorus found at 0 min 46.44 sec
Best chorus found at 5 min 0.53 sec
Best chorus found at 1 min 36.74 sec
Best chorus found at 4 min 9.93 sec
Best chorus found at 2 min 15.38 sec
Best chorus found at 2 min 35.75 sec
Best chorus found at 1 min 41.74 sec
Best chorus found at 2 min 23.94 sec
Best chorus found at 4 min 22.03 sec
Best chorus found at 2 min 7.38 sec
Best chorus found at 2 min 43.59 sec
Best chorus found at 4 min 4.25 sec
Best chorus found at 2 min 10.16 sec
Best chorus found at 3 min 36.20 sec
Best chorus found at 2 min 28.75 sec
Best chorus found at 1 min 31.52 sec
Best chorus found at 1 min 16.52 sec
Best chorus found at 0 min 56.45 sec
Best chorus found at 1 min 10.54 sec
Best chorus found at 1 min 33.96 sec
Best chorus found at 2 min 8.41 sec
Best chorus found at 1 min 21.72 sec
Best chorus found at 1 min 18.72 sec
Best chorus found at 2 min 5.65 sec
No choruses were detected. Try a smaller search duration
No choruses were detected. Try a smaller search duration
Best chorus found at 2 min 20.71 sec
Best chorus found at 1 min 52.83 sec
Best chorus found at 2 min 14.53 sec
Best chorus found at 1 min 0.89 sec
Best chorus found at 1 min 18.16 sec
Best chorus found at 1 min 19.31 sec
Best chorus found at 3 min 12.23 sec
Best chorus found at 2 min 22.90 sec
Best chorus found at 2 min 34.83 sec
Best chorus found at 3 min 16.01 sec
Best chorus found at 2 min 47.64 sec
Best chorus found at 3 min 21.68 sec
Best chorus found at 2 min 55.82 sec
Best chorus found at 2 min 12.57 sec
Best chorus found at 1 min 53.57 sec
Best chorus found at 2 min 22.44 sec
Best chorus found at 1 min 8.51 sec

In [ ]:
len(not_extrated) # check total number of not extracted songs

25

In [ ]:
extracted_song_basename = [song.replace('.wav','') for song in os.listdir('chorus_extract')] # get extracteds songs basename
extracted_song_list = [] # list for songs from table present in successful extraction list
for song in df['song_path']:
    basename = os.path.basename(song).replace('.mp3','')
    if  basename in extracted_song_basename:
        extracted_song_list.append(r'chorus_extract\{basename}.wav'.format(basename = basename)) # append successfuly extracted songs to list
    else:
        extracted_song_list.append('n/a') # append not available if extracted song does not exist

In [ ]:
len(extracted_song_list)

781

In [ ]:
df = df.assign(extracted_chorus_path=extracted_song_list) # add new exteacted chorus paths to data table
df

,Artist,Title,Label,song_path,extracted_chorus_path
0,Kendrick Lamar,Not Like Us,1,popular\Not Like Us.mp3,chorus_extract\Not Like Us.wav
1,Sabrina Carpenter,Espresso,1,popular\Espresso.mp3,chorus_extract\Espresso.wav
2,Taylor Swift,Cruel Summer,1,popular\Cruel Summer.mp3,chorus_extract\Cruel Summer.wav
3,Billie Eilish,Birds Of A Feather,1,popular\Birds Of A Feather.mp3,chorus_extract\Birds Of A Feather.wav
4,Sabrina Carpenter,Please Please Please,1,popular\Please Please Please.mp3,chorus_extract\Please Please Please.wav
...,...,...,...,...,...
788,Katy Perry,Thinking Of You,0,unpopular\Thinking Of You.mp3,chorus_extract\Thinking Of You.wav
789,Miley Cyrus,Hoedown Throwdown,0,unpopular\Hoedown Throwdown.mp3,chorus_extract\Hoedown Throwdown.wav
790,Taylor Swift,You're Not Sorry,0,unpopular\You're Not Sorry.mp3,chorus_extract\You're Not Sorry.wav
791,Rihanna,Rehab,0,unpopular\Rehab.mp3,chorus_extract\Rehab.wav
792,Usher,Trading Places,0,unpopular\Trading Places.mp3,chorus_extract\Trading Places.wav

In [ ]:
df[df['extracted_chorus_path']=='n/a'] # check for non available extracts path from list of chorus path

,Artist,Title,Label,song_path,extracted_chorus_path
25,Kendrick Lamar,Euphoria,1,popular\Euphoria.mp3,n/a
82,Bad Bunny,Despues de La Playa,1,popular\Despues de La Playa.mp3,n/a
211,XXXTENTACION,Look At Me!,1,popular\Look At Me!.mp3,n/a
252,Beyonce,11-Jul,1,popular\11-Jul.mp3,n/a
256,Sam Smith,Lay Me Down,1,popular\Lay Me Down.mp3,n/a
395,Kendrick Lamar,Reincarnated,0,unpopular\Reincarnated.mp3,n/a
402,Zach Bryan,High Road,0,unpopular\High Road.mp3,n/a
411,Eminem,Renaissance,0,unpopular\Renaissance.mp3,n/a
422,Drake,You Broke My Heart,0,unpopular\You Broke My Heart.mp3,n/a
436,Drake,Wick Man,0,unpopular\Wick Man.mp3,n/a
446,Zach Bryan,Oklahoma Smokeshow,0,unpopular\Oklahoma Smokeshow.mp3,n/a
462,SZA,Blind,0,unpopular\Blind.mp3,n/a
467,SZA,SOS,0,unpopular\SOS.mp3,n/a
495,Camila Cabello,I'll Be Home For Christmas,0,unpopular\I'll Be Home For Christmas.mp3,n/a
525,Justin Bieber,2 Much,0,unpopular\2 Much.mp3,n/a
526,DaBaby,Masterpiece,0,unpopular\Masterpiece.mp3,n/a
573,The Weeknd,Until I Bleed Out,0,unpopular\Until I Bleed Out.mp3,n/a
585,Cardi B,Press,0,unpopular\Press.mp3,n/a
699,The Chainsmokers,#SELFIE,0,unpopular\#SELFIE.mp3,n/a
704,Eminem,Rap God,0,unpopular\Rap God.mp3,n/a
728,One Direction,One Way Or Another (Teenage Kicks),0,unpopular\One Way Or Another (Teenage Kicks).mp3,n/a
743,Beyonce,Love On Top,0,unpopular\Love On Top.mp3,n/a
756,Coldplay,Every Teardrop Is A Waterfall,0,unpopular\Every Teardrop Is A Waterfall.mp3,n/a
765,Coldplay,Christmas Lights,0,unpopular\Christmas Lights.mp3,n/a
787,Lil Wayne,Hot Revolver,0,unpopular\Hot Revolver.mp3,n/a

In [ ]:
#save table to csv file
df.to_csv('extracted_chorus_incomplete.csv', index=False) # dataset with incomplete extracted choruses

In [ ]:
data1 = pd.read_csv('extracted_chorus_incomplete.csv')
data1.isna().sum() # get total number of non available extracted paths

Artist                    0
Title                     0
Label                     0
song_path                 0
extracted_chorus_path    25
dtype: int64

In [ ]:
data1 = data1.dropna() # drop rows with non available extract path
data1.isna().sum()

Artist                   0
Title                    0
Label                    0
song_path                0
extracted_chorus_path    0
dtype: int64

In [ ]:
#save table to csv file
data1.to_csv('extracted_chorus_03.csv', index=False)

# Extract audio features of the hooks using Librosa.
librosa is a python package for music and audio analysis. It provides the building blocks necessary to create music information retrieval systems.





## major features to extract :
- chroma_stft
- chroma_cqt
- chroma_cens
- mfcc
- rms
- spectral_centroid
- spectral_bandwidth
- spectral_contrast
- spectral_rolloff
- tonnetz
- zero_crossing_rate

In [ ]:
# import necessary libraries
import numpy as np
import pandas as pd
import librosa
from glob import glob

In [ ]:
df = pd.read_csv('extracted_chorus_03.csv')
df.head()

,Artist,Title,Label,song_path,extracted_chorus_path
0,Kendrick Lamar,Not Like Us,1,popular\Not Like Us.mp3,chorus_extract\Not Like Us.wav
1,Sabrina Carpenter,Espresso,1,popular\Espresso.mp3,chorus_extract\Espresso.wav
2,Taylor Swift,Cruel Summer,1,popular\Cruel Summer.mp3,chorus_extract\Cruel Summer.wav
3,Billie Eilish,Birds Of A Feather,1,popular\Birds Of A Feather.mp3,chorus_extract\Birds Of A Feather.wav
4,Sabrina Carpenter,Please Please Please,1,popular\Please Please Please.mp3,chorus_extract\Please Please Please.wav

In [ ]:
from scipy.stats import skew, kurtosis  # import libs for statistics

In [ ]:
paths = list(df['extracted_chorus_path']) # list for extracted chorus paths
titles = list(df['Title']) # list of song titles
data = [] # list to contain extracted audio features

In [ ]:
# helper function to get statistics of each dimension data for each audio raw feature
def statistics(list, feature, columns_name, data):
    i = 0 # label to track the number of raw dimensions for each audio feature
    for ele in list:
        # get the 7 statististics of each raw dimension
        _skew = skew(ele)
        columns_name.append(f'{feature}_kew_{i}')
        min = np.min(ele)
        columns_name.append(f'{feature}_min_{i}')
        max = np.max(ele)
        columns_name.append(f'{feature}_max_{i}')
        std = np.std(ele)
        columns_name.append(f'{feature}_std_{i}')
        mean = np.mean(ele)
        columns_name.append(f'{feature}_mean_{i}')
        median = np.median(ele)
        columns_name.append(f'{feature}_median_{i}')
        _kurtosis = kurtosis(ele)
        columns_name.append(f'{feature}_kurtosis_{i}')

        i += 1
        # append 7 statistics as single row in list
        data.append(_skew)
        data.append(min)
        data.append(max)
        data.append(std)
        data.append(mean)
        data.append(median)
        data.append(_kurtosis)

    return data

In [ ]:
# helper function ectract audio feature with statistics
def extract_features(audio_path, title):

    data = []
    columns_name = ['title']
    data.append(title)
    x , sr = librosa.load(audio_path)

    chroma_stft = librosa.feature.chroma_stft(y=x, sr=sr)
    statistics(chroma_stft, 'chroma_stft', columns_name, data)

    chroma_cqt = librosa.feature.chroma_cqt(y=x, sr=sr)
    statistics(chroma_cqt, 'chroma_cqt', columns_name, data)

    chroma_cens = librosa.feature.chroma_cens(y=x, sr=sr)
    statistics(chroma_cens, 'chroma_cens', columns_name, data)

    mfcc = librosa.feature.mfcc(y=x, sr=sr)
    statistics(mfcc, 'mfcc', columns_name, data)

    rms = librosa.feature.rms(y=x)
    statistics(rms, 'rms', columns_name, data)

    spectral_centroid = librosa.feature.spectral_centroid(y=x , sr=sr)
    statistics(spectral_centroid, 'spectral_centroid', columns_name, data)

    spectral_bandwidth = librosa.feature.spectral_bandwidth(y=x , sr=sr)
    statistics(spectral_bandwidth, 'spectral_bandwidth', columns_name, data)

    spectral_contrast = librosa.feature.spectral_contrast(y=x , sr=sr)
    statistics(spectral_contrast, 'spectral_contrast', columns_name, data)

    spectral_rolloff = librosa.feature.spectral_rolloff(y=x , sr=sr)
    statistics(spectral_rolloff, 'spectral_rolloff', columns_name, data)

    tonnetz = librosa.feature.tonnetz(y=x , sr=sr)
    statistics(tonnetz, 'tonnetz', columns_name, data)

    zero_crossing_rate = librosa.feature.zero_crossing_rate(y=x)
    statistics(zero_crossing_rate, 'zero_crossing_rate', columns_name, data)

    return data, columns_name

In [ ]:
# extract audio freatures for all songs chosuses/Hook
i = 0
while i < len(paths):
    audio_path = paths[i]
    d, cols = extract_features(audio_path, titles[i])
    data.append(d)
    print(f'The {i} song Done...')
    i += 1

The 0 song Done...
The 1 song Done...
The 2 song Done...
The 3 song Done...
The 4 song Done...
The 5 song Done...
The 6 song Done...
The 7 song Done...
The 8 song Done...
The 9 song Done...
The 10 song Done...
The 11 song Done...
The 12 song Done...
The 13 song Done...
The 14 song Done...
The 15 song Done...
The 16 song Done...
The 17 song Done...
The 18 song Done...
The 19 song Done...
The 20 song Done...
The 21 song Done...
The 22 song Done...
The 23 song Done...
The 24 song Done...
The 25 song Done...
The 26 song Done...
The 27 song Done...
The 28 song Done...
The 29 song Done...
The 30 song Done...
The 31 song Done...
The 32 song Done...
The 33 song Done...
The 34 song Done...
The 35 song Done...
The 36 song Done...
The 37 song Done...
The 38 song Done...
The 39 song Done...
The 40 song Done...
The 41 song Done...
The 42 song Done...
The 43 song Done...
The 44 song Done...
The 45 song Done...
The 46 song Done...
The 47 song Done...
The 48 song Done...
The 49 song Done...
The 50 song Done...
The 51 song Done...
The 52 song Done...
The 53 song Done...
The 54 song Done...
The 55 song Done...
The 56 song Done...
The 57 song Done...
The 58 song Done...
The 59 song Done...
The 60 song Done...
The 61 song Done...
The 62 song Done...
The 63 song Done...
The 64 song Done...
The 65 song Done...
The 66 song Done...
The 67 song Done...
The 68 song Done...
The 69 song Done...
The 70 song Done...
The 71 song Done...
The 72 song Done...
The 73 song Done...
The 74 song Done...
The 75 song Done...
The 76 song Done...
The 77 song Done...
The 78 song Done...
The 79 song Done...
The 80 song Done...
The 81 song Done...
The 82 song Done...
The 83 song Done...
The 84 song Done...
The 85 song Done...
The 86 song Done...
The 87 song Done...
The 88 song Done...
The 89 song Done...
The 90 song Done...
The 91 song Done...
The 92 song Done...
The 93 song Done...
The 94 song Done...
The 95 song Done...
The 96 song Done...
The 97 song Done...
The 98 song Done...
The 99 song Done...
The 100 song Done...
The 101 song Done...
The 102 song Done...
The 103 song Done...
The 104 song Done...
The 105 song Done...
The 106 song Done...
The 107 song Done...
The 108 song Done...
The 109 song Done...
The 110 song Done...
The 111 song Done...
The 112 song Done...
The 113 song Done...
The 114 song Done...
The 115 song Done...
The 116 song Done...
The 117 song Done...
The 118 song Done...
The 119 song Done...
The 120 song Done...
The 121 song Done...
The 122 song Done...
The 123 song Done...
The 124 song Done...
The 125 song Done...
The 126 song Done...
The 127 song Done...
The 128 song Done...
The 129 song Done...
The 130 song Done...
The 131 song Done...
The 132 song Done...
The 133 song Done...
The 134 song Done...
The 135 song Done...
The 136 song Done...
The 137 song Done...
The 138 song Done...
The 139 song Done...
The 140 song Done...
The 141 song Done...
The 142 song Done...
The 143 song Done...
The 144 song Done...
The 145 song Done...
The 146 song Done...
The 147 song Done...
The 148 song Done...
The 149 song Done...
The 150 song Done...
The 151 song Done...
The 152 song Done...
The 153 song Done...
The 154 song Done...
The 155 song Done...
The 156 song Done...
The 157 song Done...
The 158 song Done...
The 159 song Done...
The 160 song Done...
The 161 song Done...
The 162 song Done...
The 163 song Done...
The 164 song Done...
The 165 song Done...
The 166 song Done...
The 167 song Done...
The 168 song Done...
The 169 song Done...
The 170 song Done...
The 171 song Done...
The 172 song Done...
The 173 song Done...
The 174 song Done...
The 175 song Done...
The 176 song Done...
The 177 song Done...
The 178 song Done...
The 179 song Done...
The 180 song Done...
The 181 song Done...
The 182 song Done...
The 183 song Done...
The 184 song Done...
The 185 song Done...
The 186 song Done...
The 187 song Done...
The 188 song Done...
The 189 song Done...
The 190 song Done...
The 191 song Done...
The 192 song Done...
The 193 song Done...
The 194 song Done...
The 195 song Done...
The 196 song Done...
The 197 song Done...
The 198 song Done...
The 199 song Done...
The 200 song Done...
The 201 song Done...
The 202 song Done...
The 203 song Done...
The 204 song Done...
The 205 song Done...
The 206 song Done...
The 207 song Done...
The 208 song Done...
The 209 song Done...
The 210 song Done...
The 211 song Done...
The 212 song Done...
The 213 song Done...
The 214 song Done...
The 215 song Done...
The 216 song Done...
The 217 song Done...
The 218 song Done...
The 219 song Done...
The 220 song Done...
The 221 song Done...
The 222 song Done...
The 223 song Done...
The 224 song Done...
The 225 song Done...
The 226 song Done...
The 227 song Done...
The 228 song Done...
The 229 song Done...
The 230 song Done...
The 231 song Done...
The 232 song Done...
The 233 song Done...
The 234 song Done...
The 235 song Done...
The 236 song Done...
The 237 song Done...
The 238 song Done...
The 239 song Done...
The 240 song Done...
The 241 song Done...
The 242 song Done...
The 243 song Done...
The 244 song Done...
The 245 song Done...
The 246 song Done...
The 247 song Done...
The 248 song Done...
The 249 song Done...
The 250 song Done...
The 251 song Done...
The 252 song Done...
The 253 song Done...
The 254 song Done...
The 255 song Done...
The 256 song Done...
The 257 song Done...
The 258 song Done...
The 259 song Done...
The 260 song Done...
The 261 song Done...
The 262 song Done...
The 263 song Done...
The 264 song Done...
The 265 song Done...
The 266 song Done...
The 267 song Done...
The 268 song Done...
The 269 song Done...
The 270 song Done...
The 271 song Done...
The 272 song Done...
The 273 song Done...
The 274 song Done...
The 275 song Done...
The 276 song Done...
The 277 song Done...
The 278 song Done...
The 279 song Done...
The 280 song Done...
The 281 song Done...
The 282 song Done...
The 283 song Done...
The 284 song Done...
The 285 song Done...
The 286 song Done...
The 287 song Done...
The 288 song Done...
The 289 song Done...
The 290 song Done...
The 291 song Done...
The 292 song Done...
The 293 song Done...
The 294 song Done...
The 295 song Done...
The 296 song Done...
The 297 song Done...
The 298 song Done...
The 299 song Done...
The 300 song Done...
The 301 song Done...
The 302 song Done...
The 303 song Done...
The 304 song Done...
The 305 song Done...
The 306 song Done...
The 307 song Done...
The 308 song Done...
The 309 song Done...
The 310 song Done...
The 311 song Done...
The 312 song Done...
The 313 song Done...
The 314 song Done...
The 315 song Done...
The 316 song Done...
The 317 song Done...
The 318 song Done...
The 319 song Done...
The 320 song Done...
The 321 song Done...
The 322 song Done...
The 323 song Done...
The 324 song Done...
The 325 song Done...
The 326 song Done...
The 327 song Done...
The 328 song Done...
The 329 song Done...
The 330 song Done...
The 331 song Done...
The 332 song Done...
The 333 song Done...
The 334 song Done...
The 335 song Done...
The 336 song Done...
The 337 song Done...
The 338 song Done...
The 339 song Done...
The 340 song Done...
The 341 song Done...
The 342 song Done...
The 343 song Done...
The 344 song Done...
The 345 song Done...
The 346 song Done...
The 347 song Done...
The 348 song Done...
The 349 song Done...
The 350 song Done...
The 351 song Done...
The 352 song Done...
The 353 song Done...
The 354 song Done...
The 355 song Done...
The 356 song Done...
The 357 song Done...
The 358 song Done...
The 359 song Done...
The 360 song Done...
The 361 song Done...
The 362 song Done...
The 363 song Done...
The 364 song Done...
The 365 song Done...
The 366 song Done...
The 367 song Done...
The 368 song Done...
The 369 song Done...
The 370 song Done...
The 371 song Done...
The 372 song Done...
The 373 song Done...
The 374 song Done...
The 375 song Done...
The 376 song Done...
The 377 song Done...
The 378 song Done...
The 379 song Done...
The 380 song Done...
The 381 song Done...
The 382 song Done...
The 383 song Done...
The 384 song Done...
The 385 song Done...
The 386 song Done...
The 387 song Done...
The 388 song Done...
The 389 song Done...
The 390 song Done...
The 391 song Done...
The 392 song Done...
The 393 song Done...
The 394 song Done...
The 395 song Done...
The 396 song Done...
The 397 song Done...
The 398 song Done...
The 399 song Done...
The 400 song Done...
The 401 song Done...
The 402 song Done...
The 403 song Done...
The 404 song Done...
The 405 song Done...
The 406 song Done...
The 407 song Done...
The 408 song Done...
The 409 song Done...
The 410 song Done...
The 411 song Done...
The 412 song Done...
The 413 song Done...
The 414 song Done...
The 415 song Done...
The 416 song Done...
The 417 song Done...
The 418 song Done...
The 419 song Done...
The 420 song Done...
The 421 song Done...
The 422 song Done...
The 423 song Done...
The 424 song Done...
The 425 song Done...
The 426 song Done...
The 427 song Done...
The 428 song Done...
The 429 song Done...
The 430 song Done...
The 431 song Done...
The 432 song Done...
The 433 song Done...
The 434 song Done...
The 435 song Done...
The 436 song Done...
The 437 song Done...
The 438 song Done...
The 439 song Done...
The 440 song Done...
The 441 song Done...
The 442 song Done...
The 443 song Done...
The 444 song Done...
The 445 song Done...
The 446 song Done...
The 447 song Done...
The 448 song Done...
The 449 song Done...
The 450 song Done...
The 451 song Done...
The 452 song Done...
The 453 song Done...
The 454 song Done...
The 455 song Done...
The 456 song Done...
The 457 song Done...
The 458 song Done...
The 459 song Done...
The 460 song Done...
The 461 song Done...
The 462 song Done...
The 463 song Done...
The 464 song Done...
The 465 song Done...
The 466 song Done...
The 467 song Done...
The 468 song Done...
The 469 song Done...
The 470 song Done...
The 471 song Done...
The 472 song Done...
The 473 song Done...
The 474 song Done...
The 475 song Done...
The 476 song Done...
The 477 song Done...
The 478 song Done...
The 479 song Done...
The 480 song Done...
The 481 song Done...
The 482 song Done...
The 483 song Done...
The 484 song Done...
The 485 song Done...
The 486 song Done...
The 487 song Done...
The 488 song Done...
The 489 song Done...
The 490 song Done...
The 491 song Done...
The 492 song Done...
The 493 song Done...
The 494 song Done...
The 495 song Done...
The 496 song Done...
The 497 song Done...
The 498 song Done...
The 499 song Done...
The 500 song Done...
The 501 song Done...
The 502 song Done...
The 503 song Done...
The 504 song Done...
The 505 song Done...
The 506 song Done...
The 507 song Done...
The 508 song Done...
The 509 song Done...
The 510 song Done...
The 511 song Done...
The 512 song Done...
The 513 song Done...
The 514 song Done...
The 515 song Done...
The 516 song Done...
The 517 song Done...
The 518 song Done...
The 519 song Done...
The 520 song Done...
The 521 song Done...
The 522 song Done...
The 523 song Done...
The 524 song Done...
The 525 song Done...
The 526 song Done...
The 527 song Done...
The 528 song Done...
The 529 song Done...
The 530 song Done...
The 531 song Done...
The 532 song Done...
The 533 song Done...
The 534 song Done...
The 535 song Done...
The 536 song Done...
The 537 song Done...
The 538 song Done...
The 539 song Done...
The 540 song Done...
The 541 song Done...
The 542 song Done...
The 543 song Done...
The 544 song Done...
The 545 song Done...
The 546 song Done...
The 547 song Done...
The 548 song Done...
The 549 song Done...
The 550 song Done...
The 551 song Done...
The 552 song Done...
The 553 song Done...
The 554 song Done...
The 555 song Done...
The 556 song Done...
The 557 song Done...
The 558 song Done...
The 559 song Done...
The 560 song Done...
The 561 song Done...
The 562 song Done...
The 563 song Done...
The 564 song Done...
The 565 song Done...
The 566 song Done...
The 567 song Done...
The 568 song Done...
The 569 song Done...
The 570 song Done...
The 571 song Done...
The 572 song Done...
The 573 song Done...
The 574 song Done...
The 575 song Done...
The 576 song Done...
The 577 song Done...
The 578 song Done...
The 579 song Done...
The 580 song Done...
The 581 song Done...
The 582 song Done...
The 583 song Done...
The 584 song Done...
The 585 song Done...
The 586 song Done...
The 587 song Done...
The 588 song Done...
The 589 song Done...
The 590 song Done...
The 591 song Done...
The 592 song Done...
The 593 song Done...
The 594 song Done...
The 595 song Done...
The 596 song Done...
The 597 song Done...
The 598 song Done...
The 599 song Done...
The 600 song Done...
The 601 song Done...
The 602 song Done...
The 603 song Done...
The 604 song Done...
The 605 song Done...
The 606 song Done...
The 607 song Done...
The 608 song Done...
The 609 song Done...
The 610 song Done...
The 611 song Done...
The 612 song Done...
The 613 song Done...
The 614 song Done...
The 615 song Done...
The 616 song Done...
The 617 song Done...
The 618 song Done...
The 619 song Done...
The 620 song Done...
The 621 song Done...
The 622 song Done...
The 623 song Done...
The 624 song Done...
The 625 song Done...
The 626 song Done...
The 627 song Done...
The 628 song Done...
The 629 song Done...
The 630 song Done...
The 631 song Done...
The 632 song Done...
The 633 song Done...
The 634 song Done...
The 635 song Done...
The 636 song Done...
The 637 song Done...
The 638 song Done...
The 639 song Done...
The 640 song Done...
The 641 song Done...
The 642 song Done...
The 643 song Done...
The 644 song Done...
The 645 song Done...
The 646 song Done...
The 647 song Done...
The 648 song Done...
The 649 song Done...
The 650 song Done...
The 651 song Done...
The 652 song Done...
The 653 song Done...
The 654 song Done...
The 655 song Done...
The 656 song Done...
The 657 song Done...
The 658 song Done...
The 659 song Done...
The 660 song Done...
The 661 song Done...
The 662 song Done...
The 663 song Done...
The 664 song Done...
The 665 song Done...
The 666 song Done...
The 667 song Done...
The 668 song Done...
The 669 song Done...
The 670 song Done...
The 671 song Done...
The 672 song Done...
The 673 song Done...
The 674 song Done...
The 675 song Done...
The 676 song Done...
The 677 song Done...
The 678 song Done...
The 679 song Done...
The 680 song Done...
The 681 song Done...
The 682 song Done...
The 683 song Done...
The 684 song Done...
The 685 song Done...
The 686 song Done...
The 687 song Done...
The 688 song Done...
The 689 song Done...
The 690 song Done...
The 691 song Done...
The 692 song Done...
The 693 song Done...
The 694 song Done...
The 695 song Done...
The 696 song Done...
The 697 song Done...
The 698 song Done...
The 699 song Done...
The 700 song Done...
The 701 song Done...
The 702 song Done...
The 703 song Done...
The 704 song Done...
The 705 song Done...
The 706 song Done...
The 707 song Done...
The 708 song Done...
The 709 song Done...
The 710 song Done...
The 711 song Done...
The 712 song Done...
The 713 song Done...
The 714 song Done...
The 715 song Done...
The 716 song Done...
The 717 song Done...
The 718 song Done...
The 719 song Done...
The 720 song Done...
The 721 song Done...
The 722 song Done...
The 723 song Done...
The 724 song Done...
The 725 song Done...
The 726 song Done...
The 727 song Done...
The 728 song Done...
The 729 song Done...
The 730 song Done...
The 731 song Done...
The 732 song Done...
The 733 song Done...
The 734 song Done...
The 735 song Done...
The 736 song Done...
The 737 song Done...
The 738 song Done...
The 739 song Done...
The 740 song Done...
The 741 song Done...
The 742 song Done...
The 743 song Done...
The 744 song Done...
The 745 song Done...
The 746 song Done...
The 747 song Done...
The 748 song Done...
The 749 song Done...
The 750 song Done...
The 751 song Done...
The 752 song Done...
The 753 song Done...
The 754 song Done...
The 755 song Done...

In [ ]:
newData = pd.DataFrame(data, columns=cols) # create dataframe for new extracted audio features
newData

,title,chroma_stft_kew_0,chroma_stft_min_0,chroma_stft_max_0,chroma_stft_std_0,chroma_stft_mean_0,chroma_stft_median_0,chroma_stft_kurtosis_0,chroma_stft_kew_1,chroma_stft_min_1,...,tonnetz_mean_5,tonnetz_median_5,tonnetz_kurtosis_5,zero_crossing_rate_kew_0,zero_crossing_rate_min_0,zero_crossing_rate_max_0,zero_crossing_rate_std_0,zero_crossing_rate_mean_0,zero_crossing_rate_median_0,zero_crossing_rate_kurtosis_0
0,Not Like Us,-0.783536,0.006558,1.0,0.314549,0.741508,0.928698,-0.976357,-0.756187,0.007130,...,0.035636,0.034047,0.676838,3.048267,0.002441,0.438477,0.057799,0.048859,0.029785,13.754533
1,Espresso,0.450830,0.016104,1.0,0.314074,0.470509,0.407069,-1.049098,0.759627,0.027349,...,0.003156,0.000307,0.072464,1.140953,0.031738,0.343262,0.050428,0.115937,0.107910,2.054605
2,Cruel Summer,0.547714,0.012357,1.0,0.301537,0.456038,0.373836,-0.954753,0.081864,0.024955,...,0.030297,0.027616,0.383525,1.938092,0.022461,0.384766,0.046358,0.104179,0.099854,7.694862
3,Birds Of A Feather,0.351066,0.017149,1.0,0.297003,0.448398,0.405992,-1.068147,0.376908,0.038416,...,-0.025801,-0.021898,2.490374,2.660477,0.004395,0.247559,0.031565,0.040208,0.031250,9.727915
4,Please Please Please,1.370743,0.018626,1.0,0.219382,0.331120,0.277287,1.610433,0.390606,0.006292,...,0.009640,-0.003136,-0.395896,1.923701,0.019043,0.392090,0.046442,0.086993,0.077148,6.910997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,Thinking Of You,1.299750,0.031860,1.0,0.216751,0.305064,0.250493,1.434959,1.640333,0.023932,...,0.019917,0.014464,-0.920996,0.679809,0.078125,0.241699,0.026076,0.146740,0.144043,0.735215
752,Hoedown Throwdown,0.456860,0.008508,1.0,0.303645,0.449399,0.391693,-0.994293,0.596811,0.016852,...,-0.004066,-0.003143,1.864594,2.325682,0.029785,0.504395,0.057756,0.114507,0.102051,8.640021
753,You're Not Sorry,1.671492,0.005184,1.0,0.198032,0.219907,0.161144,2.929615,1.144193,0.006660,...,0.017369,0.007103,-0.623548,1.811186,0.048340,0.328125,0.032025,0.120847,0.116211,8.307566
754,Rehab,0.387944,0.039217,1.0,0.284192,0.527899,0.459697,-1.059349,0.770280,0.050248,...,0.008593,0.004926,-0.488677,0.473262,0.017090,0.238281,0.041259,0.112521,0.107910,-0.224298
755,Trading Places,0.272677,0.022122,1.0,0.332756,0.509989,0.440859,-1.424796,0.255652,0.037969,...,-0.044600,-0.039570,0.160994,1.006705,0.011230,0.291504,0.051638,0.093307,0.082764,0.900167

In [ ]:
df # previous data table

,Artist,Title,Label,song_path,extracted_chorus_path
0,Kendrick Lamar,Not Like Us,1,popular\Not Like Us.mp3,chorus_extract\Not Like Us.wav
1,Sabrina Carpenter,Espresso,1,popular\Espresso.mp3,chorus_extract\Espresso.wav
2,Taylor Swift,Cruel Summer,1,popular\Cruel Summer.mp3,chorus_extract\Cruel Summer.wav
3,Billie Eilish,Birds Of A Feather,1,popular\Birds Of A Feather.mp3,chorus_extract\Birds Of A Feather.wav
4,Sabrina Carpenter,Please Please Please,1,popular\Please Please Please.mp3,chorus_extract\Please Please Please.wav
...,...,...,...,...,...
751,Katy Perry,Thinking Of You,0,unpopular\Thinking Of You.mp3,chorus_extract\Thinking Of You.wav
752,Miley Cyrus,Hoedown Throwdown,0,unpopular\Hoedown Throwdown.mp3,chorus_extract\Hoedown Throwdown.wav
753,Taylor Swift,You're Not Sorry,0,unpopular\You're Not Sorry.mp3,chorus_extract\You're Not Sorry.wav
754,Rihanna,Rehab,0,unpopular\Rehab.mp3,chorus_extract\Rehab.wav
755,Usher,Trading Places,0,unpopular\Trading Places.mp3,chorus_extract\Trading Places.wav

In [ ]:
final_data = df.join(newData) # join both datasets of same number of rows
final_data

,Artist,Title,Label,song_path,extracted_chorus_path,title,chroma_stft_kew_0,chroma_stft_min_0,chroma_stft_max_0,chroma_stft_std_0,...,tonnetz_mean_5,tonnetz_median_5,tonnetz_kurtosis_5,zero_crossing_rate_kew_0,zero_crossing_rate_min_0,zero_crossing_rate_max_0,zero_crossing_rate_std_0,zero_crossing_rate_mean_0,zero_crossing_rate_median_0,zero_crossing_rate_kurtosis_0
0,Kendrick Lamar,Not Like Us,1,popular\Not Like Us.mp3,chorus_extract\Not Like Us.wav,Not Like Us,-0.783536,0.006558,1.0,0.314549,...,0.035636,0.034047,0.676838,3.048267,0.002441,0.438477,0.057799,0.048859,0.029785,13.754533
1,Sabrina Carpenter,Espresso,1,popular\Espresso.mp3,chorus_extract\Espresso.wav,Espresso,0.450830,0.016104,1.0,0.314074,...,0.003156,0.000307,0.072464,1.140953,0.031738,0.343262,0.050428,0.115937,0.107910,2.054605
2,Taylor Swift,Cruel Summer,1,popular\Cruel Summer.mp3,chorus_extract\Cruel Summer.wav,Cruel Summer,0.547714,0.012357,1.0,0.301537,...,0.030297,0.027616,0.383525,1.938092,0.022461,0.384766,0.046358,0.104179,0.099854,7.694862
3,Billie Eilish,Birds Of A Feather,1,popular\Birds Of A Feather.mp3,chorus_extract\Birds Of A Feather.wav,Birds Of A Feather,0.351066,0.017149,1.0,0.297003,...,-0.025801,-0.021898,2.490374,2.660477,0.004395,0.247559,0.031565,0.040208,0.031250,9.727915
4,Sabrina Carpenter,Please Please Please,1,popular\Please Please Please.mp3,chorus_extract\Please Please Please.wav,Please Please Please,1.370743,0.018626,1.0,0.219382,...,0.009640,-0.003136,-0.395896,1.923701,0.019043,0.392090,0.046442,0.086993,0.077148,6.910997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,Katy Perry,Thinking Of You,0,unpopular\Thinking Of You.mp3,chorus_extract\Thinking Of You.wav,Thinking Of You,1.299750,0.031860,1.0,0.216751,...,0.019917,0.014464,-0.920996,0.679809,0.078125,0.241699,0.026076,0.146740,0.144043,0.735215
752,Miley Cyrus,Hoedown Throwdown,0,unpopular\Hoedown Throwdown.mp3,chorus_extract\Hoedown Throwdown.wav,Hoedown Throwdown,0.456860,0.008508,1.0,0.303645,...,-0.004066,-0.003143,1.864594,2.325682,0.029785,0.504395,0.057756,0.114507,0.102051,8.640021
753,Taylor Swift,You're Not Sorry,0,unpopular\You're Not Sorry.mp3,chorus_extract\You're Not Sorry.wav,You're Not Sorry,1.671492,0.005184,1.0,0.198032,...,0.017369,0.007103,-0.623548,1.811186,0.048340,0.328125,0.032025,0.120847,0.116211,8.307566
754,Rihanna,Rehab,0,unpopular\Rehab.mp3,chorus_extract\Rehab.wav,Rehab,0.387944,0.039217,1.0,0.284192,...,0.008593,0.004926,-0.488677,0.473262,0.017090,0.238281,0.041259,0.112521,0.107910,-0.224298
755,Usher,Trading Places,0,unpopular\Trading Places.mp3,chorus_extract\Trading Places.wav,Trading Places,0.272677,0.022122,1.0,0.332756,...,-0.044600,-0.039570,0.160994,1.006705,0.011230,0.291504,0.051638,0.093307,0.082764,0.900167

In [ ]:
final_data.columns # scan for repeated column names

Index(['Artist', 'Title', 'Label', 'song_path', 'extracted_chorus_path',
       'title', 'chroma_stft_kew_0', 'chroma_stft_min_0', 'chroma_stft_max_0',
       'chroma_stft_std_0',
       ...
       'tonnetz_mean_5', 'tonnetz_median_5', 'tonnetz_kurtosis_5',
       'zero_crossing_rate_kew_0', 'zero_crossing_rate_min_0',
       'zero_crossing_rate_max_0', 'zero_crossing_rate_std_0',
       'zero_crossing_rate_mean_0', 'zero_crossing_rate_median_0',
       'zero_crossing_rate_kurtosis_0'],
      dtype='object', length=524)

In [ ]:
final_data = final_data.drop(columns=['title'], axis=1) #drop repeated colunm name

In [ ]:
final_data.columns

Index(['Artist', 'Title', 'Label', 'song_path', 'extracted_chorus_path',
       'chroma_stft_kew_0', 'chroma_stft_min_0', 'chroma_stft_max_0',
       'chroma_stft_std_0', 'chroma_stft_mean_0',
       ...
       'tonnetz_mean_5', 'tonnetz_median_5', 'tonnetz_kurtosis_5',
       'zero_crossing_rate_kew_0', 'zero_crossing_rate_min_0',
       'zero_crossing_rate_max_0', 'zero_crossing_rate_std_0',
       'zero_crossing_rate_mean_0', 'zero_crossing_rate_median_0',
       'zero_crossing_rate_kurtosis_0'],
      dtype='object', length=523)

In [ ]:
#save table to csv file
final_data.to_csv('feature_extract_04.csv', index=False)